### ISSUE TITLE
Error setting up gladys bluetooth

### ISSUE THREAD

**Issue by kalon33** [GladysProject/gladys-bluetooth#1]
I followed instructions at https://gladysproject.com/fr/article/detecter-presence-porte-cle-bluetooth

But got error in Gladys:

```
0|app      | Error: NotFound
0|app      |     at /root/gladys/api/core/utils/utils.sqlUnique.js:8:39
0|app      |     at tryCatcher (/root/gladys/node_modules/bluebird/js/release/util.js:16:23)
0|app      |     at Promise._settlePromiseFromHandler (/root/gladys/node_modules/bluebird/js/release/promise.js:512:31)
0|app      |     at Promise._settlePromise (/root/gladys/node_modules/bluebird/js/release/promise.js:569:18)
0|app      |     at Promise._settlePromise0 (/root/gladys/node_modules/bluebird/js/release/promise.js:614:10)
0|app      |     at Promise._settlePromises (/root/gladys/node_modules/bluebird/js/release/promise.js:693:18)
0|app      |     at Promise._fulfill (/root/gladys/node_modules/bluebird/js/release/promise.js:638:18)
0|app      |     at /root/gladys/node_modules/bluebird/js/release/nodeback.js:42:21
0|app      |     at /root/gladys/node_modules/sails-mysql/lib/connections/spawn.js:120:16
0|app      |     at Object.poolfully [as releaseConnection] (/root/gladys/node_modules/sails-mysql/lib/connections/release.js:28:12)
0|app      |     at Query._callback (/root/gladys/node_modules/sails-mysql/lib/connections/spawn.js:105:35)
0|app      |     at Query.Sequence.end (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
0|app      |     at Query._handleFinalResultPacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
0|app      |     at Query.EofPacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
0|app      |     at Protocol._parsePacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
0|app      |     at Parser.write (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
0|app      |     at Protocol.write (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
0|app      |     at Socket.<anonymous> (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
0|app      |     at emitOne (events.js:115:13)
0|app      |     at Socket.emit (events.js:210:7)
0|app      |     at addChunk (_stream_readable.js:266:12)
0|app      |     at readableAddChunk (_stream_readable.js:253:11)
0|app      |     at Socket.Readable.push (_stream_readable.js:211:10)
0|app      |     at TCP.onread (net.js:585:20)
```
and gladys-bluetooth:
```

Starting Bluetooth Scan for 30 seconds !
Found Bluetooth peripheral, name = One, id = f3431f016b02, address = f3:43:1f:01:6b:02.
Error while sending data to Gladys
{ StatusCodeError: 403 - undefined
    at new StatusCodeError (/root/gladys-bluetooth/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/root/gladys-bluetooth/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/root/gladys-bluetooth/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/root/gladys-bluetooth/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/root/gladys-bluetooth/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/root/gladys-bluetooth/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 403,
  message: '403 - undefined',
  error: undefined,
  options: 
   { method: 'POST',
     uri: 'http://localhost:8080/device?token=your-gladys-token',
     body: { device: [Object], types: [Array] },
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 389,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 248,
        [Symbol(bytesRead)]: 343 },
     connection: 
      Socket {
        _jar: undefined,
        port: '8080',
        host: 'localhost',
        path: '/device?token=your-gladys-token',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://localhost:8080/device?token=your-gladys-token',
        req: [Object],
        ntick: true,
        response: [Object],
        originalHost: 'localhost:8080',
        originalHostHeaderName: 'host',
        responseContent: [Object],
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function] } }
403
Stopping Bluetooth Scan for 60 seconds !
Bluetooth Scan stopped
```
and couldn't set up bluetooth detection properly. How could I fix that? Is that a bug? I had to install bluetooth on my raspbian, as it wasn't installed. Thanks!

**Comment by kalon33** [comment]
Ok forget it, I forgot the token, as it wasn't described in the blog post, but I should have noticed it in the config file. Sorry, I'm going to sleep ;)
